update description project motion
01-edu/public pull request #1039
Opened 2022-03-29 11:10 UTC by davidrobert99

2022-04-18 10:22 UTC, LEEDASILVA commented on subjects/project_motion/README.md
> +#[derive(Debug, Clone, PartialEq)]
do not know, but could be nice to change the name to `Point` or `coordinate`? let me know what you think

2022-04-18 10:22 UTC, LEEDASILVA commented on subjects/project_motion/README.md
> +$$ v(t) =  v_{0} + a*t $$
has discussed between us, in LaTex this looks nice but do not know why github is not rendering this. So maybe we could change it using \`\`

2022-05-05 17:23 UTC, MSilva95 requested changes
Left some comments for some changes

2022-05-20 11:38 UTC, MSilva95 approved these changes

2022-05-24 14:50 UTC, merged