Update exams exercises rust public c 562
01-edu/public pull request #1099
Opened 2022-05-27 00:38 UTC by davidrobert99

2022-05-30 08:35 UTC, MSilva95 requested changes
Solve conflict in tuples

2022-05-31 16:08 UTC, davidrobert99 commented
> Solve conflict in tuples

Done.

2022-06-01 17:48 UTC, davhojt approved these changes

2022-06-02 15:15 UTC, MSilva95 approved these changes

2022-06-04 21:46 UTC, merged