9 review language piscine rustroad c 396
01-edu/public pull request #1110
Opened 2022-06-01 20:58 UTC by davhojt

Language review of road_intersection raid

2022-06-02 17:23 UTC, MSilva95 requested changes
I just feel like we could explain a little bit the arrows part, other than that its a go...

2022-06-02 17:23 UTC, MSilva95 commented on subjects/road_intersection/README.md
> +- **`↑` Up:** south to north.
or maybe just add 
**`↑` Up:** direction south to north.

2022-06-03 06:38 UTC, davhojt commented on subjects/road_intersection/README.md
> +```
The problem is that it road really wide which makes it look like it has many lanes in each direction. I'll leave it like this, but perhaps it is better to replace it entirely with an image.

2022-06-03 06:40 UTC, davhojt commented on subjects/road_intersection/README.md
> +- **`↑` Up:** south to north.
Agreed. I made a change.

2022-06-03 16:13 UTC, MSilva95 commented on subjects/road_intersection/README.md
> +```
its ok like this, if they read carefully they will get it

2022-06-03 16:14 UTC, MSilva95 commented on subjects/road_intersection/README.md
> +```
its ok like this, if they read carefully they will get it

2022-06-03 16:14 UTC, MSilva95 approved these changes

2022-06-12 21:45 UTC, merged