add(subject): alphaPostion
01-edu/public pull request #1201
Opened 2022-06-11 13:24 UTC by Hamzaelkhatri

2022-06-13 21:33 UTC, mohamedLazyBob approved these changes

2022-06-15 09:40 UTC, davidrobert99 requested changes

2022-06-15 09:40 UTC, davidrobert99 commented on subjects/alphaposition/README.md
> +## instructions
Missing an # and "i" should be in upper case ("Instructions")

2022-06-15 09:40 UTC, davidrobert99 commented on subjects/alphaposition/README.md
> +### usage
The u should be in upper case also "Usage"

2022-06-15 09:40 UTC, davidrobert99 commented on subjects/alphaposition/README.md
> +### output
Instead of using a heading it should one be "And its output :"

2022-06-15 09:52 UTC, davidrobert99 approved these changes

2022-06-22 15:14 UTC, merged