add same-case subject
01-edu/public pull request #1231
Opened 2022-06-15 19:00 UTC by zainabdnaya

2022-06-15 19:54 UTC, Hamzaelkhatri requested changes
add this case : 
```console 
$ go run . | cat -e 
$
$ go run A B | cat -e 
1$

2022-06-17 17:13 UTC, Hamzaelkhatri approved these changes

2022-06-30 15:02 UTC, MSilva95 requested changes

2022-06-30 15:02 UTC, MSilva95 commented on subjects/samecase/REDME.md
> +
here you need to add the instruction for when you have multiple chars...

`- if you have more than one character per argument do this...`

2022-06-30 15:31 UTC, zainabdnaya commented on subjects/samecase/REDME.md
> +- All outputs should be followed by a new-line character
In Line 10, it has been mentioned or is preferred to use in each sentence, "Followed by a newline."

2022-07-03 11:33 UTC, zainabdnaya commented on subjects/samecase/REDME.md
> +$go run . "p" "4"  | cat -e
fixed

2022-07-03 11:38 UTC, zainabdnaya commented on subjects/samecase/REDME.md
> +$go run . A b  | cat -e
fixed

2022-07-03 11:38 UTC, zainabdnaya commented on subjects/samecase/REDME.md
> +-1$
fixed

2022-07-14 15:19 UTC, MSilva95 commented on subjects/samecase/REDME.md
> +- All outputs should be followed by a new-line character
Yes i saw what you said in line 10, but i think it looks better like i suggested, you don't need to say (all outputs... character)

2022-07-14 15:25 UTC, MSilva95 requested changes

2022-07-14 15:47 UTC, zainabdnaya commented on subjects/zappy/audit/README.md
> +### Functional
I delete it

2022-07-14 16:36 UTC, MSilva95 approved these changes

2022-08-04 11:00 UTC, merged