Add Subject of Concat 2 arguments
01-edu/public pull request #1247
Opened 2022-06-16 21:08 UTC by zainabdnaya

2022-06-17 16:52 UTC, Hamzaelkhatri approved these changes

2022-07-08 11:05 UTC, MSilva95 requested changes

2022-07-08 23:29 UTC, zainabdnaya commented on subjects/concat2argument/README.md
> +$ go run . " student " talented | cat -e
An argument can be with "" or without , so no matter whether the argument is with or without ""  it should be concatenated.

2022-07-13 09:49 UTC, zainabdnaya commented on subjects/concat2argument/README.md
> +Write a program that concatenates two arguments  and prints the result:
done

2022-07-13 09:49 UTC, zainabdnaya commented on subjects/concat2argument/README.md
> +- don't concatenate the two arguments with space.
explained

2022-07-13 10:05 UTC, zainabdnaya commented on subjects/concat2argument/README.md
> +$ go run . " student " talented | cat -e
To avoid confusion,  I put quotes  in all arguments

2022-07-13 10:05 UTC, zainabdnaya commented on subjects/concat2argument/README.md
> +$ go run . "Hello" "student" talented ! | cat -e
Corrected

2022-07-14 17:12 UTC, MSilva95 commented on subjects/concat2argument/README.md
> +$ go run . " student " talented | cat -e
I know that it can be with or without the quotation marks but you need to be consistent.

2022-07-18 14:57 UTC, MSilva95 requested changes

2022-08-04 17:32 UTC, MSilva95 approved these changes

2024-09-03 14:54 UTC, closed without merging