docs: Add description for oddlength
01-edu/public pull request #1286
Opened 2022-06-23 11:14 UTC by eslopfer

Readme for oddlength

2022-06-23 11:32 UTC, Hamzaelkhatri approved these changes

2022-06-30 16:37 UTC, MSilva95 requested changes

2022-06-30 16:37 UTC, MSilva95 commented on subjects/oddlength/README.md
> +Write a function that receives a slice of strings and returns a new slice with the strings in which the length is odd.
explain what happens when its an empty slice or when there is none odd strings

2022-06-30 16:37 UTC, MSilva95 commented on subjects/oddlength/README.md
> +import (
Remove the piscine imports and the variable, just print it

2022-07-05 10:39 UTC, MSilva95 requested changes

2022-07-05 10:39 UTC, MSilva95 commented on subjects/oddlength/README.md
> +    fmt.Println(Oddlength(["Hi", "Hola", "Ola", "Ciao", "Salut", "Hallo"]))
This is not correct, i think what you need is this:
`fmt.Println(Oddlength([]string{"Hi", "Hola", "Ola", "Ciao", "Salut", "Hallo"}`))

2022-07-12 17:28 UTC, MSilva95 approved these changes

2022-07-14 07:29 UTC, merged