DEV-3881-docs: Add readme for sumthemall subject
01-edu/public pull request #1301
Opened 2022-06-30 10:09 UTC by eslopfer

Add readme for sumthemall subject

2022-06-30 11:03 UTC, Hamzaelkhatri reviewed
can you add, if the argument is not a number display `0` or `"Error\n"`

2022-06-30 12:46 UTC, eslopfer commented
> can you add, if the argument is not a number display `0` or `"Error\n"`

Wouldn't this be one of the unrealistic scenarios, since we are telling the student that the program is going to be tested with numbers, and we are the ones writing the tests?

2022-07-08 14:46 UTC, Hamzaelkhatri approved these changes

2022-07-27 15:47 UTC, MSilva95 requested changes

2022-07-27 15:47 UTC, MSilva95 commented on subjects/sumthemall/README.md
> +Create a program that receives a number of arguments representing whole numbers and displays the sum of the total. If there are not enough arguments or there is an overflow display 0 followed by a ne
Do you think its good like this?

```
Create a program that takes integers as arguments and displays the sum total of all of them. If it is not a number, there are not enough arguments, or if there is an overflow, print `0` followed by a newline.
```

2022-11-09 12:44 UTC, tiagocollot commented on subjects/sumthemall/README.md
> +Create a program that receives a number of arguments representing whole numbers and displays the sum of the total. If there are not enough arguments or there is an overflow display 0 followed by a ne
It is fixed.

2022-11-09 14:55 UTC, jotapero approved these changes
LGTM :alien:

2022-12-22 22:34 UTC, merged