subject of wordfflip
01-edu/public pull request #1354
Opened 2022-07-29 02:08 UTC by zainabdnaya

2022-08-10 11:10 UTC, jotapero requested changes

2022-08-10 16:53 UTC, jotapero approved these changes

2022-11-02 15:43 UTC, jotapero requested changes

2022-11-08 11:15 UTC, tiagocollot commented on subjects/wordflip/README.md
> +- Ignore spaces if it's more then one space in between words and all spaces in the edge of the words or sentences.
It is fixed.

2022-11-08 11:15 UTC, tiagocollot commented on subjects/wordflip/README.md
> +Write a function `WordFlip()` that receives a `string` and returns it with the first and last words flipped.
It is fixed.

2022-11-09 14:34 UTC, jotapero approved these changes
LGTM :alien:

2022-11-14 07:10 UTC, eslopfer requested changes

2022-11-14 07:10 UTC, eslopfer commented on subjects/wordflip/README.md
> +- Prints the Output followed by newline `\n`.
In the previous line you said that it returns, should it print or return?

2022-11-14 07:10 UTC, eslopfer commented on subjects/wordflip/README.md
> +func WordFlip(str string) string {
From this signature it appears that the function should return, but before it's asked to print.

2023-06-19 17:15 UTC, merged