DEV-3188-new-go-exercise-halfslice
01-edu/public pull request #1363
Opened 2022-07-31 00:19 UTC by Hamzaelkhatri

2022-08-04 10:15 UTC, jotapero requested changes

2022-08-04 10:47 UTC, Hamzaelkhatri commented on subjects/halfslice/README.md
> +## half-Slice
fixed , thank you

2022-08-04 10:47 UTC, Hamzaelkhatri commented on subjects/halfslice/README.md
> +	fmt.Println(HalfSlice([]int{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}))
fixed

2022-08-04 14:45 UTC, jotapero approved these changes
All good

2022-09-06 09:22 UTC, jotapero approved these changes

2022-09-23 10:47 UTC, jotapero approved these changes

2022-11-03 15:05 UTC, jotapero approved these changes
Looks Good :alien:

2022-11-14 07:58 UTC, eslopfer approved these changes
LGTM! :rocket:

2023-06-20 11:05 UTC, merged