Dev 3389 new go exercise display s
01-edu/public pull request #1376
Opened 2022-08-04 21:12 UTC by Hamzaelkhatri

2022-11-02 16:59 UTC, tiagocollot requested changes

2022-11-02 16:59 UTC, tiagocollot commented on subjects/displays/README.md
> +Write a program that displays an `S` character on the standard followed by newlines (`'\n'`)
Instructions need to be fixed. I would suggest --> "Write a program that displays a character `S` followed by a newline `\n`."

2022-11-09 14:40 UTC, tiagocollot approved these changes
LGTM ⚡️

2022-11-14 09:27 UTC, eslopfer approved these changes
LGTM! :rocket:

2022-12-05 11:20 UTC, merged