feat(piscine-go): add README.md for new go exercise dealapackofcards
01-edu/public pull request #1430
Opened 2022-09-08 17:44 UTC by tiagocollot

Created and added new go exercise dealapackofcards.

2022-09-23 11:01 UTC, jotapero approved these changes

2022-09-26 13:42 UTC, eslopfer requested changes

2022-09-26 13:42 UTC, eslopfer commented on subjects/dealapackofcards/README.md
> +Write a function `DealAPackOfCards()` that takes an argument `deck` as an `int` and prints the desired output.
Slice of int

2022-09-26 13:42 UTC, eslopfer commented on subjects/dealapackofcards/README.md
> +```go
Console instead of go.

2022-10-03 15:37 UTC, tiagocollot commented on subjects/dealapackofcards/README.md
> +```go
It is fixed.

2022-10-17 17:13 UTC, eslopfer approved these changes
LGTM! :rocket:

2022-10-18 10:23 UTC, merged