DEV-3388-new-go-exercise-displayp-subject
01-edu/public pull request #1526
Opened 2022-10-19 16:37 UTC by jotapero

- docs(displayP): created new subject
- PR did not exist

2022-11-02 16:14 UTC, tiagocollot requested changes

2022-11-07 14:40 UTC, jotapero commented on subjects/displays/README.md
> +
fixed

2022-11-07 14:40 UTC, jotapero commented on subjects/displays/README.md
> +Write a program that displays an `P` character on the standard followed by newlines (`'\n'`)
fixed

2022-11-09 13:43 UTC, jotapero commented on subjects/displays/README.md
> +
fixed

2022-11-09 14:31 UTC, tiagocollot approved these changes
LGTM!

2022-11-14 09:21 UTC, eslopfer submitted a review, later dismissed

2022-11-14 09:21 UTC, eslopfer commented on subjects/displayp/README.md
> +```
Please run prettier

2022-12-05 17:18 UTC, merged