DEV-3805 add new rust exercise
01-edu/public pull request #1580
Opened 2022-11-17 14:37 UTC by nprimo

2022-11-19 15:05 UTC, mikysett requested changes
Maybe let's clarify what a lucas number is to allow more focus on the recursion part

2022-11-21 15:17 UTC, nprimo commented on subjects/lucas_number/README.md
> +
Agree! I will add this

2022-11-21 16:29 UTC, mikysett approved these changes
LGTM

2022-11-21 16:30 UTC, mikysett approved these changes
LGTM

2022-11-21 17:29 UTC, merged