DEV-3899 add subject, test and solution for the exercise change-struct
01-edu/public pull request #1612
Opened 2022-11-30 17:28 UTC by MSilva95

2022-11-30 21:23 UTC, zamazzal requested changes

2022-11-30 21:23 UTC, zamazzal commented on subjects/change-struct/README.md
> +**Tips:**
tips should be in H3

2022-12-06 10:06 UTC, zamazzal commented
you have to move the subject folder inside subject/devops folder

2022-12-09 16:49 UTC, MSilva95 commented on subjects/change-struct/README.md
> +**Tips:**
Done

2022-12-12 20:52 UTC, zamazzal requested changes
i can't understand why you have this folders inside the 'solutions' folder:

- 0_to_3
- 4
- 6_to_9
- A

2022-12-14 17:35 UTC, zamazzal approved these changes

2022-12-16 09:59 UTC, merged