Dev 3747 new exercise about handling different http request methods
01-edu/public pull request #1624
Opened 2022-12-05 18:28 UTC by eslopfer

2022-12-15 15:23 UTC, mikysett requested changes
In order to check the tests may you add the solution in the `piscine-js-solutions` repo please

2022-12-15 15:23 UTC, mikysett commented on subjects/uninvited/README.md
> +To test your program, you should be able to expect the following behaviour once your program is up and running.
small typo on "behavior"

2022-12-19 13:21 UTC, nprimo commented on js/tests/test.mjs
> +global._fetch = fetch
This change has already been implemented and merged in the current master version - I guess having it in this PR should not impact the final `master` version

2022-12-19 13:29 UTC, nprimo commented on subjects/uninvited/README.md
> +- [Node http package: createServer](https://nodejs.org/en/knowledge/HTTP/servers/how-to-create-a-HTTP-server/)
I would add this link as well on how to read data from a POST request 
https://nodejs.org/en/knowledge/HTTP/servers/how-to-read-POST-data/

2022-12-19 13:38 UTC, nprimo commented on js/tests/uninvited_test.mjs
> +import fss from 'fs'
This is imported but not used

2022-12-19 13:49 UTC, nprimo requested changes
I have added a few inline comments. 

Moreover, all the changes made to `test.mjs` are already implemented in the current `master` repo version - I don't know if it make sense to include these changes in this PR as well. Overall it should not influence the final result of `master` after this PR is merged

2022-12-20 07:40 UTC, nprimo approved these changes
LGTM!

2022-12-21 10:18 UTC, mikysett requested changes

2022-12-21 10:18 UTC, mikysett commented on .gitignore
> +js/soluss
here a newline is missing at the end of the file, maybe we could put it back, this also will prevent for seeing a change in the `.gitignore` while actually nothing changed.

2022-12-21 10:18 UTC, mikysett commented on subjects/uninvited/README.md
> +  "food": "bats"
maybe it's worth changing also `bats` to something more neutral.

2022-12-21 10:18 UTC, mikysett commented on subjects/uninvited/README.md
> +To test your program, you should be able to expect the following behaviour once your program is up and running.
actually it's not a typo, just UK English... I've checked in the curriculum, there is both versions, US `behavior` and UK `behaviour`, in our subjects.
I have to say we have more times the US version than the UK, I suggest we use that one, but I have no strong opinion so feel free to chose the path you prefer about it.

2022-12-22 10:24 UTC, mikysett approved these changes
LGTM

2022-12-28 11:51 UTC, merged