DEV-3904-find-files-extension
01-edu/public pull request #1628
Opened 2022-12-06 08:47 UTC by zamazzal

…exercise

2022-12-06 14:34 UTC, nprimo requested changes

2022-12-07 14:55 UTC, zamazzal commented on sh/tests/find-files-extension_test.sh
> +
fixed

2022-12-07 14:57 UTC, zamazzal commented on subjects/devops/find-files-extension/README.md
> +<..>/find-files-extension-example
I used pwd to indicate that the user should be inside the folder find-files-example

2022-12-07 14:58 UTC, zamazzal commented on subjects/devops/find-files-extension/README.md
> +Create a file `find-files-extension.sh`, which will look, from the current directory and its sub-folders for:
I prefer this way cause it's serves the context better

2022-12-07 16:25 UTC, nprimo reviewed
Please, let me know if the `README.md` is supposed to be in this specific sub-directory instead of `public/subjects/`

2022-12-09 08:35 UTC, nprimo approved these changes
LGTM!

2022-12-09 09:04 UTC, merged