DEV-4309 race bring issue from public
01-edu/public pull request #1748
Opened 2023-01-23 15:03 UTC by eslopfer

### Why?

When running the solution you always get the same error `Promise.race is undefined`

### Solution Overview

Promise.race was set to undefined in the test of the exercise, and because the script that runs the tests uses it it would always show an error. The solution I proposed is to save it in another property and  check  whether Promise.race is undefined when running the tests.

### Implementation Details

Assuming the reason to set this method to undefined is to avoid 'cheating', other ways this could be implemented could be to obfuscate the name of Promise.race_ to something more meaningless, and perhaps store it outside of  `Promise`.
Another possible way could be to implement the functionality from scratch, but this would be the actual solution for the exercise and it could also  be copied, so it would defeat the purpose of preventing cheating.

My opinion is that we can't prevent cheating in all scenarios. It's very likely there will always be a way. I think that making it not the path of less resistance is enough, that's why I chose the current implementation. I am against obfuscating code, since code should be written to be read, and we are already preventing the easy 'cheat' of using the built in method.

2023-01-25 07:22 UTC, davhojt requested changes
We could consider to:
- Remove `Promise.race = undefined`.
- Modify the exercise, make it get the last promise - so that they cannot use `Promise.race`

Note, I have temporarily made commented out `Promise.race = undefined` in this commit: https://github.com/01-edu/public/commit/a08e1968865190d133300029f86edc304a4e2cf2. So you'll need to rebase that into your branch and get rid of those comments.

2023-01-25 14:44 UTC, eslopfer commented on js/tests/test.mjs
> +      const waitWithTimeout = Promise.race
Thanks, I reverted it to how it was before.

2023-01-25 14:47 UTC, eslopfer commented
Since the second part of the solution for this exercise requires to understand Promise.race, we discussed that there isn't actually a need to prevent cheating with the Promise.race since the learner will need to understand it to pass the tests for the some function.

2023-01-26 15:38 UTC, davhojt requested changes
This PR modifies a lot of code and files which are not in the scope of this change.
As the behaviour in master is achieved, this PR essentially needs to remove the commented lines which are present in master.

If we intend to perform stylistic changes, let's do that as a PR for all of the tests.

2023-01-26 17:15 UTC, eslopfer commented
> This PR modifies a lot of code and files which are not in the scope of this change. As the behaviour in master is achieved, this PR essentially needs to remove the commented lines which are present in master.
> 
> If we intend to perform stylistic changes, let's do that as a PR for all of the tests.

That was automatically formatted and didn't see it, my bad. I reverted it to how it was.

2023-01-27 14:27 UTC, davhojt approved these changes
LGTM.

Squash merge, to get rid of the irrelevant commits.

2023-01-30 07:25 UTC, merged