DEV-4318-merge-two
01-edu/public pull request #1763
Opened 2023-01-24 16:25 UTC by mikysett

add new python exercise to scripting piscine

subject and tests/solution should be merged at the same time

2023-01-24 17:38 UTC, nprimo commented on subjects/devops/merge_two/README.md
> +- There is different ways to merge dictionaries, take the time to understand the differences in between those techniques and try more than one technique to better retain it.
It should be 
```
- There are different ways ... 
```

2023-01-24 18:26 UTC, nprimo reviewed
In the JIRA ticker it is mentioned to convert the dictionary to JSON - is there a particular reason this has not been introduced into the subject?

2023-01-27 10:31 UTC, mikysett commented on subjects/devops/merge_two/README.md
> +- There is different ways to merge dictionaries, take the time to understand the differences in between those techniques and try more than one technique to better retain it.
done

2023-01-27 15:46 UTC, mikysett commented
Thanks a lot for pointing out `JSON` features are missing.
I've implemented it now, also `stdin` input was supposed to be implemented but I think it will be way too much work to properly implement a test for this situation. I've started a thread with @zamazzal to see what he thinks could be the best approach

2023-01-31 09:22 UTC, nprimo commented on subjects/devops/merge_two/README.md
> +- [Function input() in Python](https://www.w3schools.com/python/ref_func_input.asp)
I get this after running `prettier`

```console
diff --git a/subjects/devops/merge_two/README.md b/subjects/devops/merge_two/README.md
index e8feea74..21ff1da9 100644
--- a/subjects/devops/merge_two/README.md
+++ b/subjects/devops/merge_two/README.md
@@ -70,4 +70,4 @@ $

 - [Merging dictionaries in Python](https://www.geeksforgeeks.org/python-merging-two-dictionaries/)
 - [JSON library in Python](https://docs.python.org/3/library/json.html)
-- [Function input() in Python](https://www.w3schools.com/python/ref_func_input.asp)
\ No newline at end of file
+- [Function input() in Python](https://www.w3schools.com/python/ref_func_input.asp)
(END)
```

2023-01-31 10:15 UTC, nprimo commented on subjects/devops/merge_two/README.md
> +It will prompt the user to create a new dictionary asking for keys and values.
Maybe add also something like: 
```
The function will always try to convert the `values` to integer
```

2023-01-31 11:13 UTC, nprimo requested changes
I left 2 comments inline

2023-01-31 14:08 UTC, mikysett commented on subjects/devops/merge_two/README.md
> +- [Function input() in Python](https://www.w3schools.com/python/ref_func_input.asp)
done

2023-01-31 14:11 UTC, mikysett commented on subjects/devops/merge_two/README.md
> +It will prompt the user to create a new dictionary asking for keys and values.
done

2023-01-31 16:30 UTC, nprimo approved these changes
LGTM :rocket:

2023-01-31 18:21 UTC, merged