DEV-4325: read_file
01-edu/public pull request #1771
Opened 2023-01-26 15:19 UTC by MSilva95

> Before starting, please choose the relevant pull request **Labels**, **Reviewers**, and **Assignees**

### Why?

> Clearly state the reason for this change. What problem is it solving or feature is it adding?

### Solution Overview

> Provide an overview of the solution implemented in this pull request. This should be a high level overview without getting into technical details. If applicable, include screenshots of UI or use GitHub compliant [`mermaid`](https://mermaid.live/) graphs to visually represent the solution.

### Implementation Details

> Explain the details of the implementation and the reasoning behind it. What alternative approaches were considered and why was this approach chosen?

2023-01-26 19:04 UTC, eslopfer requested changes
Some minor suggestions for accurate meaning.

2023-01-31 14:08 UTC, MSilva95 commented on subjects/devops/read_file/README.md
> +Create another file `recipes_data.json` and copy/paste on it the following content:
done

2023-01-31 14:09 UTC, MSilva95 commented on subjects/devops/read_file/README.md
> +You have to read the file `recipes_data.json` and load its content into a list of dictionaries.
done

2023-01-31 14:12 UTC, MSilva95 commented on subjects/devops/read_file/README.md
> +Create a file `read_file.py` which will have a function `get_recipes(file_name)` that takes a file as an argument.
i just added the highlight to `file` because in the function they already see that it will be the file name `get_recipes(file_name)`

2023-02-01 07:44 UTC, eslopfer commented on subjects/devops/read_file/README.md
> +Create a file `read_file.py` which will have a function `get_recipes(file_name)` that takes a file as an argument.
It looks clear to me, that is not the same thing the `file`, which means the actual file, the bits of it, that the `file_name` or the `file_path`, but if you think it's ok as it is, you can resolve this conversation, proceed and merge it.

2023-02-01 10:44 UTC, MSilva95 commented on subjects/devops/read_file/README.md
> +Create a file `read_file.py` which will have a function `get_recipes(file_name)` that takes a file as an argument.
i've changed it thanks

2023-02-01 11:15 UTC, eslopfer approved these changes
LGTM! :rocket:

2023-02-01 11:16 UTC, merged