CON-1810-MARKDOWN-drawing-raid-for-Java-piscine
01-edu/public pull request #2099
Opened 2023-07-25 08:58 UTC by Hamzaelkhatri

docs(Jart):add the audit of jart raid

> Before starting, please choose the relevant pull request **Labels**, **Reviewers**, and **Assignees**

### Why?

> Clearly state the reason for this change. What problem is it solving or feature is it adding?

### Solution Overview

> Provide an overview of the solution implemented in this pull request. This should be a high level overview without getting into technical details. If applicable, include screenshots of UI or use GitHub compliant [`mermaid`](https://mermaid.live/) graphs to visually represent the solution.

### Implementation Details

> Explain the details of the implementation and the reasoning behind it. What alternative approaches were considered and why was this approach chosen?

2023-07-27 02:54 UTC, zanninso commented on subjects/java/raids/Jart/README.md
the interface Displayable its not used here at all you can remove it while the image.save used to result the image or use display from Displayable interface to produce the image and require for the student to produce the image by opening a file and writing the pixels there you can use the easiest image format for not make it hard

2023-07-27 02:57 UTC, zanninso commented on subjects/java/raids/Jart/audit/README.md
ask the students about the interfaces and if it's well used and implemented 
you can ask also if the student use a default implementation of in the interfaces it self

2023-07-27 02:58 UTC, zanninso requested changes
please resolve the added conversations

2023-07-27 10:26 UTC, Hamzaelkhatri commented on subjects/java/raids/Jart/README.md
The Displayable interface is implemented in the Image class. the method `save` for example is to get it from the Displayable interface

2023-07-27 15:57 UTC, zanninso requested changes

2023-07-27 18:05 UTC, Hamzaelkhatri commented on subjects/java/raids/Jart/README.md
from the example, the student should understand that the `Image` class implements `Displayable`. and Displayable contains two functions `display` and  `save`

```java
interface Displayable {
    void display(int x, int y, Color color);

    void save(String string);
}
```
display function used inside `Drawable` as a parameter of the `draw` function 

```java
interface Drawable {
    void draw(Displayable displayable);
   //...
}
```

> I add the `save`  function in the subject in the part of  `Displayable` interface to make it more clear.

2023-07-28 02:35 UTC, zanninso commented on subjects/java/raids/Jart/README.md
there is no details of the interfaces methods signature in the subject and this make it harder even for me to understand, and in this way we keep a gap where students can do a lot of mistakes you have to specify the signatures of the interfaces methodes, like in the example same the object of the image into a variable of type displayable this way can give a hint to the students about the signatures and parametres types.
to recap here is what you have to change:
- add the signature of the display method that will take the corrdinates`x, y` and a color
- change the image variable type to `Displayable `

2023-07-28 15:11 UTC, Hamzaelkhatri commented on subjects/java/raids/Jart/audit/README.md
Done 👍🏻

2023-08-05 00:32 UTC, zanninso approved these changes
LGTM

2023-08-05 00:32 UTC, merged