CON-2641 canjump new exam exercise
01-edu/public pull request #2549
Opened 2024-04-22 17:46 UTC by MSilva95

CON-2641

### Why?

canjump new exam exercise

2024-04-23 19:03 UTC, nprimo requested changes

2024-05-06 17:23 UTC, MSilva95 commented on subjects/canjump/README.md
> +> Note: The function only needs to consider positive numbers or zero in the array of steps. Also remember if the input has only one element that is the last position in the array so the function will
done

2024-05-06 17:23 UTC, MSilva95 commented on subjects/canjump/README.md
> +> Note: The function only needs to consider positive numbers or zero in the array of steps. Also remember if the input has only one element that is the last position in the array so the function will
did the change thanks

2024-05-09 12:08 UTC, nprimo approved these changes
LGTM

2024-05-14 13:39 UTC, merged