CON-2672 update `repeatalpha` subject to ask for a function instead of a program
01-edu/public pull request #2587
Opened 2024-06-03 11:35 UTC by nprimo

[CON-2671](https://01talent.atlassian.net/browse/CON-2671)

2024-06-05 16:39 UTC, MSilva95 requested changes

2024-06-05 16:39 UTC, MSilva95 commented on subjects/repeatalpha/main.go
> +import (
we tend to use package piscine here, i think for the code editor it needs that

2024-06-11 15:31 UTC, MSilva95 approved these changes
LGTM!

2024-06-27 21:38 UTC, HarryVasanth approved these changes
> [!NOTE]
>  ✅ Production and pre-production prerequisites have been deployed.
> #### Clear to merge!

2024-06-27 21:39 UTC, merged