CON-2908-Markdown-Armstrong-Number-Exercise
01-edu/public pull request #2630
Opened 2024-07-03 02:32 UTC by zanninso

[CON-2908](https://01talent.atlassian.net/browse/CON-2908)

2024-07-05 17:23 UTC, MSilva95 requested changes
Format, and it's good to go.
Again, I'm not a fan of all those comments in the usage, for example why would we leave comments like " // Expected output: true " if we actually have the expected output below?

2024-07-08 00:36 UTC, zanninso commented on subjects/java/checkpoints/armstrong-number/ExerciseRunner.java
> +}
what should i format here ?

2024-07-08 01:04 UTC, zanninso commented on subjects/java/checkpoints/armstrong-number/ExerciseRunner.java
> +}
this is a java code it's formatted already

2024-07-10 16:10 UTC, MSilva95 commented on subjects/java/checkpoints/armstrong-number/ExerciseRunner.java
> +}
![image](https://github.com/01-edu/public/assets/53977751/79dc0693-b9e3-460a-a0e8-f9c37f39e372)

2024-07-10 16:12 UTC, MSilva95 approved these changes
LGTM!
You can close the conversation if you feel no need to format the runner.java

2024-07-10 16:52 UTC, merged