feat/test(DPxAI): Added the subject and modified naming for the test …
01-edu/public pull request #2645
Opened 2024-07-16 16:13 UTC by Oumaimafisaoui

https://01talent.atlassian.net/browse/CON-2948

2024-07-16 17:28 UTC, nprimo requested changes
I left some comments inline

2024-07-16 17:28 UTC, nprimo commented on dom/call-it_test.js
the exercise `the-calling` is still existing and it is used in the origin and discovery pisicine. I would copy the test instead of renaming it to avoid weird behaviour for campuses that would like to use the origin or discovery piscine

2024-07-16 17:28 UTC, nprimo commented on subjects/DPxAI/call_it/README.md
as a convention, all the names of the exercise/project directoryieshould be `kebab-case`

2024-07-16 19:29 UTC, Oumaimafisaoui commented on subjects/DPxAI/call_it/README.md
Addressed.

2024-07-18 10:10 UTC, nprimo requested changes

2024-07-18 10:10 UTC, nprimo commented on subjects/DPxAI/call_it/README.md
This file can be removed now :)

2024-07-22 08:31 UTC, nprimo approved these changes
LGTM

2024-07-22 08:31 UTC, nprimo approved these changes
LGTM

2024-07-23 09:16 UTC, merged