CON-2989 Markdown/Test ``DPxAI:Quest00/Ex06``
01-edu/public pull request #2654
Opened 2024-07-21 19:37 UTC by Oumaimafisaoui

https://01talent.atlassian.net/browse/CON-2989

2024-07-23 14:03 UTC, nprimo requested changes

2024-07-23 15:31 UTC, lotoussa commented on dom/first-move_test.js
> +  await eq.$('script', { type: 'module' })
i don't know much about js / js tests
this is copy pasted from Clement input from previous discovery piscine
i tested it manually to ensure it work and i felt like it's ok, but if your knowledge tell us that it should not be like this we can relate on you and trust your input.

2024-07-23 16:02 UTC, nprimo commented on dom/first-move_test.js
> +  await eq.$('script', { type: 'module' })
if you remove `type="module"` from the `script` tag, in the solution, the solution fails the tests, but fulfils everything explained in the subject: for this reason, I would say to remove this check.

2024-07-23 18:31 UTC, Oumaimafisaoui commented on dom/first-move_test.js
> +  await eq.$('script', { type: 'module' })
@nprim link check removed.

2024-07-24 08:19 UTC, nprimo approved these changes

2024-07-29 07:57 UTC, merged