CON-3030 Subject for ``star forge``
01-edu/public pull request #2665
Opened 2024-07-28 22:16 UTC by Oumaimafisaoui

Solve : [CON-3030]('https://01talent.atlassian.net/browse/CON-3030')

2024-08-07 10:56 UTC, nprimo commented on subjects/DPxAI/declare-everything/README.md
This file is not related to this PR

2024-08-08 16:42 UTC, nprimo requested changes
Have you checked if it's possible to have an exercise without solution/tests?
It's possible to "bypass" the need to submit a solution by adding a test that always pass and does not expect any file as solution

2024-08-12 07:57 UTC, Oumaimafisaoui commented on subjects/DPxAI/star-forge/README.md
> +1. **Open your favorite Generative AI (ChatGPT as acfdn example)**: Go to [ChatGPT](https://chatgpt.com/) and start a new chat session.
Normally, that was the plan to have a truthy instruction in test, but to prevent any unwanted issues, I added a simple task. The typos are fixed too.

2024-08-12 07:57 UTC, Oumaimafisaoui commented on subjects/DPxAI/star-forge/README.md
> +As you dive into this hackathon, using AI tools can significantly boost your learning.
It is a hackathon, but to keep it open in case they want to change that, I've put a quest.

2024-08-12 07:58 UTC, Oumaimafisaoui commented on subjects/DPxAI/star-forge/README.md
> +Similar to this technique , we will discover in each incoming exercise, a new way to learn with AI , helping you achieve your goals with your peers
Fixed

2024-08-12 08:31 UTC, nprimo commented on subjects/DPxAI/star-forge/README.md
> +### task:
task should be with a capital letter

2024-08-13 12:10 UTC, nprimo requested changes
I left a comment for a small typo / grammar fix

2024-08-14 09:47 UTC, nprimo approved these changes

2024-08-28 12:23 UTC, zanninso approved these changes
LGTM

2024-08-29 01:21 UTC, merged