Tests(DPxAI): Add test for Quest01 declare-everything
01-edu/public pull request #2670
Opened 2024-07-31 13:31 UTC by lotoussa

[CON-3027](https://01talent.atlassian.net/browse/CON-3027)

2024-08-01 13:29 UTC, nprimo requested changes
Any special reason why the tests are as `json` file instead of `js`?

2024-08-01 13:29 UTC, nprimo commented on js/tests/declare-everything_test.json
The file name needs to be `declare-everythin.json` to be run by the test image entry point

2024-08-08 08:39 UTC, nprimo approved these changes
LGTM - to be merged only when the following are approved:
- #2664
- 01-edu/solutions#47

2024-08-30 13:01 UTC, Oumaimafisaoui approved these changes
LGTM

2024-08-30 13:01 UTC, merged