CON-3063 Markdown for ``Quest01/good-recipe``
01-edu/public pull request #2678
Opened 2024-08-07 16:15 UTC by Oumaimafisaoui

[CON-3063](https://01talent.atlassian.net/browse/CON-3063)

2024-08-14 09:46 UTC, nprimo requested changes
I have left some small suggestions in line

2024-08-14 09:46 UTC, nprimo commented on subjects/DPxAI/good-recipe/README.md
> +Methods are functions called from another value. For example, toFixed is a method that formats numbers:
`toFixed` could be formatted for format consistency

2024-08-14 09:46 UTC, nprimo commented on subjects/DPxAI/good-recipe/README.md
> +Using the .slice method to cut parts of a string:
`.slice` format could improve the clarity of the subject

2024-08-20 08:45 UTC, nprimo approved these changes

2024-08-29 17:48 UTC, zanninso approved these changes

2024-08-29 17:48 UTC, merged