CON-2956 Markdown DPxAI ``Quest02/first-wink``
01-edu/public pull request #2692
Opened 2024-08-19 19:37 UTC by Oumaimafisaoui

Resolves CON-2956

2024-08-20 10:01 UTC, nprimo requested changes
Just formatting style suggestions. Everything else LGTM :rocket:

2024-08-20 10:01 UTC, nprimo commented on subjects/DPxAI/first-wink/README.md
> +- [Video](https://www.youtube.com/watch?v=m34qd7aGMBo&list=PLHyAJ_GrRtf979iZZ1N3qYMfsPj9PCCrF&index=13) on querySelector
`querySelector` could be formatted to be in line with the other subjects

2024-08-21 10:45 UTC, nprimo approved these changes
LGTM :rocket:

2024-08-30 14:04 UTC, lotoussa approved these changes

2024-08-30 14:34 UTC, merged