CON-3172 Fixing Credit Scoring project
01-edu/public pull request #2721
Opened 2024-09-12 07:58 UTC by Oumaimafisaoui

Resolves CON-3172

Changes Overview:

- Reorganized project structure for better modularity and clarity
- Split Jupyter notebook into separate Python scripts
- Enhanced documentation throughout the project

Testing:

- Ran all scripts to ensure they execute without errors
- Verified model performance meets or exceeds previous benchmarks
- Checked that all required outputs are generated correctly

2024-09-23 15:57 UTC, MSilva95 requested changes
There is quite some stuff to change, and I saw some more that I would prefer to do the change myself or speak to you directly so that I can explain better

2024-09-25 08:31 UTC, Oumaimafisaoui commented on subjects/ai/credit-scoring/README.md
> +### 1. Introduction :
fixed

2024-09-25 08:31 UTC, Oumaimafisaoui commented on subjects/ai/credit-scoring/README.md
> +- `requirements.txt` contains all libraries required to run the code.
fixed

2024-09-25 08:32 UTC, Oumaimafisaoui commented on subjects/ai/credit-scoring/README.md
> +#### a - Scoring model
fixed

2024-09-25 08:32 UTC, Oumaimafisaoui commented on subjects/ai/credit-scoring/README.md
> +  - The model is validated if the **AUC on the test set is higher than 50%**.
fixed

2024-09-25 08:32 UTC, Oumaimafisaoui commented on subjects/ai/credit-scoring/README.md
> +  - The model is validated if the **AUC on the test set is higher than 50%**.
fixed###

2024-09-25 08:32 UTC, Oumaimafisaoui commented on subjects/ai/credit-scoring/README.md
> +#### d - Optional
fixed

2024-09-25 08:32 UTC, Oumaimafisaoui commented on subjects/ai/credit-scoring/README.md
> +### 1. Introduction :
fixed

2024-10-28 12:31 UTC, closed without merging