0-shel subject and audit
01-edu/public pull request #709
Opened 2021-02-05 16:03 UTC by MSilva95

2021-02-08 11:12 UTC, LEEDASILVA requested changes

2021-02-08 11:12 UTC, LEEDASILVA commented on subjects/0-shell/audit/README.md
> +###### Can you confirm that the interpreter displayed the current path?
maybe you can add some questions like
` ##### Try to open the project and create a parent folder with two child folders using the command "mkdir". Then enter the parent folder and do "pwd" . `

`###### Can you confirm that the interpreter displayed the current path?`

2021-02-11 16:59 UTC, xpetit requested changes

2021-02-11 16:59 UTC, xpetit commented on subjects/0-shell/README.md
> +The objective of this project is for you to create a simple [shell](https://en.wikipedia.org/wiki/Shell_script).
https://en.wikipedia.org/wiki/Unix_shell looks like a more appropriate link

2021-02-11 16:59 UTC, xpetit commented on subjects/0-shell/README.md
> +For this project you will only have to create a simple `Unix` interpreter where you can run some of the most known commands. For this part of the project, no advanced functions, pipes or redirection
"shell", "Unix shell" or "command-line interpreter" but not "Unix interpreter". Unix can't be interpreted

2021-02-11 16:59 UTC, xpetit commented on subjects/0-shell/README.md
> +- You must implement the following commands that will behave exactly like the originals:
There are no originals unfortunately.
So maybe we can advise to target a simple and widespread thing, like BusyBox.

2021-02-11 16:59 UTC, xpetit commented on subjects/0-shell/README.md
> +- The project has to be written in a compiled language like (C, Rust, go or other), no semi compiled language like (Pearl and others) are allowed.
"go" => "Go"
"semi compiled" => "interpreted"
"Pearl" => "Perl"

2021-02-11 16:59 UTC, xpetit commented on subjects/0-shell/job-control/README.md
> +- disown
To follow BusyBox I would replace `disown` with `nohup` or remove this builtin entirely as it is less important.

2021-02-11 16:59 UTC, xpetit commented on subjects/0-shell/scripting/README.md
> +In `scripting` you must find a way to make your `0-shell` run `bash` scripts.
Bash is too complex and has too many advanced structures to be taken as a example.
`ash` instead ? (integrated in BusyBox and in Debian as `dash`)

2021-02-11 16:59 UTC, xpetit commented on subjects/0-shell/scripting/README.md
> +echo ${STR,}   #=> "hELLO WORLD!" (lowercase 1st letter)
This is Bash and not POSIX compliant so I would remove these string manipulations.

2021-02-24 18:11 UTC, xpetit approved these changes

2021-02-25 16:21 UTC, LEEDASILVA approved these changes

2021-03-02 17:01 UTC, merged