Raid#1 - Carbon copy
01-edu/public pull request #734
Opened 2021-02-22 10:38 UTC by MarieMalarme

2021-02-22 10:39 UTC, MarieMalarme commented
Jus missing to indicate what is optional in the JS interactions phase.

2021-02-22 15:02 UTC, kigiri requested changes
Hate de voir les retours des etudiants dessus ca me semble vraiment bien

2021-02-22 15:02 UTC, kigiri commented on subjects/carbon-copy/README.md
> +- [`setInterval`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval)
on s'en sert quand du `setInterval` la ? j'ai rater un truc ?

2021-02-22 15:02 UTC, kigiri commented on subjects/carbon-copy/README.md
> +- When clicking on a card, open a modal window that will show the whole article ; the modal will be closed either when clicking on a "Close" button, or when the "Escape" key is pressed.
coolos de gerer `escape` bienvu

2021-02-22 15:05 UTC, MarieMalarme commented on subjects/carbon-copy/README.md
> +- [`setInterval`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval)
J'ai mis dans l'option warrior de faire changer la joke de chuck norris toutes les 4 secondes !!

2021-02-22 15:05 UTC, MarieMalarme commented on subjects/carbon-copy/README.md
> +- Change the order of the pictures when clicking on the pictures' section, [toggling](https://developer.mozilla.org/fr/docs/Web/API/Element/classList) the pre-defined class `row-reverse` from the CSS
Ah c'est pas voulu haha c'est parce que par défaut ça me sort les pages en FR

2021-02-22 15:06 UTC, MarieMalarme commented on subjects/carbon-copy/README.md
> +- [Css flexbox layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox) is always useful
Ouais bin j'y ai pensé mais je pensais que on allait carrément dédier un exo à ça non ? Mais je peux mettre le lien carrément

2021-02-22 15:07 UTC, MarieMalarme commented on subjects/carbon-copy/README.md
> +- [`classList` / `toggle`](https://developer.mozilla.org/fr/docs/Web/API/Element/classList)
Ok très bien je prends css-tricks !

2021-02-22 16:58 UTC, kigiri commented on subjects/carbon-copy/README.md
> +- [`setInterval`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval)
Ah yes j'avais rater le truc, nice, ptet 4 sec c'est un peu short ?

2021-02-23 10:51 UTC, MarieMalarme commented on subjects/carbon-copy/README.md
> +- [`setInterval`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval)
J'ai mis 10 secondes, soyons confortable

2021-02-23 12:19 UTC, kigiri approved these changes

2021-02-23 12:20 UTC, merged